[PHP]
post_max_size = 100M
upload_max_filesize = 100M
memory_limit = 256M
max_execution_time = 300
display_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
date.timezone = Asia/Tokyo
mbstring.language = Japanese
mbstring.internal_encoding = UTF-8
expose_php = Off
